name: 'Test triaging'
on:
  issues:
    types: [opened]
jobs:
  triaging:
    runs-on: ubuntu-latest
    name: To check template usage
    steps:
    - name: Create comment
      uses: ./dist/
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
