name: 'Triaging'
description: "GitHub action analysing new issue for correct template usage."
author: "Arhia"
inputs:
  template-identifier: # change this
    required: true
    description: 'define identifier to be find in issue body'
    default: 'GENERATED_BY_TEMPLATE'
runs:
  using: 'node14'
  main: 'dist/index.js'
