name: 'Test triaging'
on:
  issues:
    types: [opened]
jobs:
  triaging:
    runs-on: ubuntu-latest
    name: To check template usage
    steps:
    - uses: actions/checkout@v2
    - name: Create comment
      uses: ./dist/
